# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

version: '3'
services:
  redis:
    image: redis:latest
    networks:
      - resource-network
    ports:
      - "6379:6379"
    command: --requirepass redispass

  localstack:
    image: localstack/localstack:0.9.5
    networks:
      - resource-network
    ports:
      - "4571:4571"
      - "4572:4572"
    environment:
      - SERVICES=elasticsearch,s3
      - DEFAULT_REGION=us-west-2

  postgres:
    image: postgres:9.6-alpine
    networks:
      - resource-network
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - resource-network

networks:
  resource-network:
    driver: bridge
