# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

version: '3'
services:
  redis:
    image: redis:latest
    networks:
      - resource-network
    ports:
      - "6379:6379"
    command: --requirepass redispass

  localstack:
    image: localstack/localstack:0.9.5
    networks:
      - resource-network
    ports:
      - "4571:4571"
      - "4572:4572"
    environment:
      - SERVICES=elasticsearch,s3
      - DEFAULT_REGION=us-west-2

  postgres:
    image: postgres:9.6-alpine
    networks:
      - resource-network
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - resource-network

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6380:6379"
    expose:
      - "6380"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6381:6379"
    expose:
      - "6381"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6382:6379"
    expose:
      - "6382"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6383:6379"
    expose:
      - "6383"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6384:6379"
    expose:
      - "6384"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    ports:
      - "6385:6379"
    expose:
      - "6385"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-cluster-init:
    image: docker.io/bitnami/redis-cluster:6.0-debian-10
    networks:
      - resource-network
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

networks:
  resource-network:
    driver: bridge
